services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - /frontend/.env  
    ports:
      - "3000:3000"
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - /backend/.env
    ports: 
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network
    

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dreamvacations
    volumes:
      - db-data:/var/lib/postgresql/data  # Persisting database data
    ports:
      - "5432:5432"  # Exposing the PostgreSQL port
    networks:
      - app-network

# Network definition for service communication
networks:
  app-network:
    driver: bridge

# Volumes to persist data
volumes:
  db-data:
    driver: local
